image: alpine/edge
packages:
  - git
  - elixir
sources:
  - https://git.sr.ht/~rukenshia/shipvote
secrets:
  - 39526075-910f-4eef-98f4-bfa9788aec0f
  - 1ae5be86-eab3-49fd-be80-3aebd4e33db4
environment:
  MIX_ENV: test
tasks:
  - mirror: |
      cd shipvote
      git remote set-url origin git@github.com:Rukenshia/shipvote.git
      git push origin master
      git push origin --tags
  - test: |
      cd shipvote/backend
 
      mix local.hex --force
      mix local.rebar --force
      mix deps.get
      mix test
