image: alpine/edge
packages:
  - git
sources:
  - https://git.sr.ht/~rukenshia/shipvote.git
secrets:
  - 39526075-910f-4eef-98f4-bfa9788aec0f
  - 3abe5eb9-b390-41ec-ba22-4a9056281504
tasks:
  - mirror: |
      cd shipvote
      git remote set-url origin git@github.com:Rukenshia/shipvote.git
      git push origin master
