kind: pipeline
name: backend

steps:
- name: install
  image: elixir:latest
  commands:
  - cd backend
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

- name: test
  image: elixir:latest
  commands:
  - cd backend
  - mix test

---
kind: pipeline
name: frontend

steps:
- name: build
  image: node
  commands:
  - cd frontend/shipvote-frontend
  - npm install
  - npm run build