image: alpine/edge
packages:
  - git
  - elixir
  - erlang-runtime-tools
  - erlang-tools
  - postgresql
sources:
  - https://git.sr.ht/~rukenshia/shipvote
secrets:
  - 39526075-910f-4eef-98f4-bfa9788aec0f
  - 1ae5be86-eab3-49fd-be80-3aebd4e33db4
  - c7e549a9-3b06-449d-ab54-51c492c28ca2
  - 0ea9acdb-4117-4068-bc2c-107bdba5c026
environment:
  MIX_ENV: test
tasks:
  - mirror: |
      cd shipvote
      git remote set-url origin git@github.com:Rukenshia/shipvote.git
      git push origin master
      git push origin --tags

  - setup: |
      sudo service postgresql start
      sudo su - postgres -c 'createdb shipvote'
  - test: |
      cd shipvote/backend
 
      mix local.hex --force
      mix local.rebar --force
      mix deps.get
      mix test --cover
  - compile: |
      cd shipvote/backend
      mv ~/.prod.secret.exs config/prod.secret.exs
      MIX_ENV=prod mix compile
  - deploy: |
      echo "104.248.101.163 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwM48NgaEpbJv1C1FoQlmzm4YeMvwDtAO0er8LCYCBQGKxGTDt6TyFdbXGWsXRnioG/Uqz3jtJs1+4LDRWYbcOe43kKcBDcQSewZmTc1W4nXrFE9sRrRXxinBzGoTEB66W4z5BQyKwTxQ4pcp84Ym3iUuQwESIUR0l7PAtKeHDWn4N2qF9uTh1q2XOknoF5Yc3TF2+OA8rZtGuIRohHOR2NrWAeta487TziYzwd0eg9wlt6jwsigeb/FpdvW3THG/0cb3tgTQ32INs/MYVlT8z96AOC1AdzQpy4q1/BKbxdav2RLIkPJq2slmAEUbwfZwUtrLfQm9FgvZ1tZfU5hCz" >> known_hosts

      ssh -o "UserKnownHostsFile=known_hosts" -i ~/.ssh/deploy root@104.248.101.163 < shipvote/backend/scripts/deploy.sh
triggers:
  - action: email
    condition: failure
    to: "Jan Christophersen <jan@chrstphrsn.cc>"
