image: alpine/edge
packages:
  - git
  - elixir
  - erlang-runtime-tools
  - erlang-tools
  - postgresql
  - jq
sources:
  - https://git.sr.ht/~rukenshia/shipvote
secrets:
  - 39526075-910f-4eef-98f4-bfa9788aec0f
  - 1ae5be86-eab3-49fd-be80-3aebd4e33db4
  - b516f798-17a6-4308-ad79-136b4f1b5ec7
  - 0ea9acdb-4117-4068-bc2c-107bdba5c026
  - 9608b36c-e6e0-4a60-8c78-ff89e5d201fa
environment:
  MIX_ENV: test
tasks:
  - mirror: |
      cd shipvote
      git remote set-url origin git@github.com:Rukenshia/shipvote.git
      git push origin master --force
      git push origin --tags

  - setup: |
      sudo service postgresql start
      sudo su - postgres -c 'createdb shipvote'
  - test: |
      cd shipvote/backend
 
      mix local.hex --force
      mix local.rebar --force
      mix deps.get
      mix test --cover
  - compile: |
      cd shipvote/backend
      mv ~/.prod.secret.exs config/prod.secret.exs
      MIX_ENV=prod mix compile
  - deploy: |
      # Retrieve currently deployed instances
      set +x
      ips="$(curl -H "Authorization: Bearer $(cat ~/.digitalocean_api_key)" "https://api.digitalocean.com/v2/droplets?tag_name=tier:web" | jq -r '.droplets[].networks.v4[0].ip_address')"
      set -x

      for ip in $ips; do
        ssh-keyscan -t rsa $ip >> known_hosts
        ssh -o "UserKnownHostsFile=known_hosts" -i ~/.ssh/deploy root@$ip < shipvote/backend/scripts/deploy.sh
      done
triggers:
  - action: email
    condition: always
    to: "Jan Christophersen <jan@chrstphrsn.cc>"
