image: alpine/edge
packages:
  - git
  - elixir
  - erlang-runtime-tools
  - erlang-tools
  - postgresql
sources:
  - https://git.sr.ht/~rukenshia/shipvote
secrets:
  - 39526075-910f-4eef-98f4-bfa9788aec0f
  - 1ae5be86-eab3-49fd-be80-3aebd4e33db4
  - b516f798-17a6-4308-ad79-136b4f1b5ec7
  - 0ea9acdb-4117-4068-bc2c-107bdba5c026
environment:
  MIX_ENV: test
tasks:
  - mirror: |
      cd shipvote
      git remote set-url origin git@github.com:Rukenshia/shipvote.git
      git push origin master --force
      git push origin --tags

  - setup: |
      sudo service postgresql start
      sudo su - postgres -c 'createdb shipvote'
  - test: |
      cd shipvote/backend
 
      mix local.hex --force
      mix local.rebar --force
      mix deps.get
      mix test --cover
  - compile: |
      cd shipvote/backend
      mv ~/.prod.secret.exs config/prod.secret.exs
      MIX_ENV=prod mix compile
  - deploy: |
      echo "142.93.97.76 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLlyhEAGzPgI96V4c1A9eRBLoMfERvu4LfTSYM1gUfodxAjmrI97VsN9gVPgaDwPtNMiODrpX4TuZdeIBba2sUwz39d7nE2NB529X60pM+8o+RHuFz9M1jcRDli04WpfV14UomrWVCjWIFINGzsrXOEBnML6iELkW3uJRm5N8o1gCRxTp606R/+VHIT6qICn225G1Mhronqm0nGe3gX3zz1afyS0XSX+/WmnHjqJ2hMWVR6xhMDJowkND5sIDqQTg9V91q7yBLofbzxRjmI0FGWf46wjma9uIe1cmHtu6yNrszS8Qy24wK47tKKLKhgjtEJMAH9ml35FGt2/oBcDG5" >> known_hosts

      ssh -o "UserKnownHostsFile=known_hosts" -i ~/.ssh/deploy root@142.93.97.76 < shipvote/backend/scripts/deploy.sh
triggers:
  - action: email
    condition: always
    to: "Jan Christophersen <jan@chrstphrsn.cc>"
