image: ubuntu/18.10 
packages:
  - git
  - postgresql
  - jq
  - nodejs
  - python
  - python-pip
  - awscli
  - curl
  - unzip
sources:
  - https://git.sr.ht/~rukenshia/shipvote
secrets:
  - 39526075-910f-4eef-98f4-bfa9788aec0f
  - 1ae5be86-eab3-49fd-be80-3aebd4e33db4
  - 0ea9acdb-4117-4068-bc2c-107bdba5c026
  - 9608b36c-e6e0-4a60-8c78-ff89e5d201fa
  - cb616abf-ff36-488d-8e2c-1c3b2d34226f
  - 1832b31e-e954-415c-b49d-5e0421875440
environment:
  MIX_ENV: test
tasks:
  - setup: |
      sudo apt install -yq npm
      wget -q https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_21.3.7-1~ubuntu~cosmic_amd64.deb
      sudo apt install -yq ./esl-erlang_21.3.7-1~ubuntu~cosmic_amd64.deb
      rm esl-erlang_21.3.7-1~ubuntu~cosmic_amd64.deb

      wget -q https://packages.erlang-solutions.com/erlang/elixir/FLAVOUR_2_download/elixir_1.8.1-2~ubuntu~cosmic_amd64.deb
      sudo apt install -yq ./elixir_1.8.1-2~ubuntu~cosmic_amd64.deb
      rm elixir_1.8.1-2~ubuntu~cosmic_amd64.deb

      wget https://releases.hashicorp.com/packer/1.4.1/packer_1.4.1_linux_amd64.zip
      unzip packer_1.4.1_linux_amd64.zip
      rm packer_1.4.1_linux_amd64.zip
      chmod +x ./packer
      sudo mv ./packer /usr/bin/packer

      sudo update-locale LANG=C.UTF-8
      sudo service postgresql start
      sudo su - postgres -c 'createdb shipvote'
      sudo -u postgres psql -c "alter user postgres with password 'postgres';"
  - test: |
      cd shipvote/backend
 
      mix local.hex --force
      mix local.rebar --force
      mix deps.get
      mix test --cover
  - build: |
      cd shipvote/backend
      mv ~/.prod.secret.exs config/prod.secret.exs
      MIX_ENV=prod mix compile
      cd assets
      npm ci --no-progress
      npm run deploy
      cd ..
      mix phx.digest

      MIX_ENV=prod mix release --env=prod

      mv _build/prod/rel/backend/releases/*/backend.tar.gz ../infra/backend.tar.gz
  - packer: |
      set +x
      source ~/.shipvote.aws.builds.sr.ht
      set -x

      cd shipvote/infra
      packer build ami.json
  - deploy: |
      set +x
      source ~/.shipvote.aws.builds.sr.ht
      set -x

      cd shipvote/infra

      export NEW_AMI="$(cat manifest.json | jq -r '.builds[0].artifact_id' | awk -F':' '{print $2}')"

      ./deploy.sh
triggers:
  - action: email
    condition: always
    to: "Jan Christophersen <jan@chrstphrsn.cc>"
