org: rukenshia
app: shipvote
service: shipvote-bgassign
frameworkVersion: ">=1.28.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      statements:
        - Effect: Allow
          Action:
            - ec2:DescribeInstances
            - ssm:SendCommand
            - ec2:CreateTags
          Resource: "*"

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  assign:
    handler: bin/lambda
    events:
      - schedule: rate(3 minutes)
